program aktivita akce bez znovunačtení
gamecon-cz/gamecon pull request #535
Opened 2024-06-05 22:09 UTC by Sciator

Zobrazí načítání při načítání aktivit programu (nic extra ale lepší než nic)
Při přihlašování odhlašování ... nenačítá znovu celou stránku

2024-06-06 09:54 UTC, jaroslavtyc requested changes
Ještě budeme muset dořešit jak předávat flash message - teď když si chci přihlásit aktivitu, která koliduje s jinou kterou už mám přihlášenou, tak by se mělo ukázat _V daném čase už máš přihlášenu jinou aktivitu._, ale neukáže se nic a vypadá to, jako že přihlašování nefunguje.

2024-07-23 08:41 UTC, jaroslavtyc commented on model/Aktivita/Aktivita.php
> +    public static function prihlasovatkoZpracujJSON(?Uzivatel $u, ?Uzivatel $prihlasujici, $parametry = 0)
Tohle prosím nedělejme, to je cesta do pekel :smiling_imp: 

Jediný rozdíl mezi `prihlasovatkoZpracuj` a touhle metodou je, že původní má v sobě `back`, jinak je logika stejná a my bychom si tímhle dost zavařili, protože bychom museli udržovat stejnou logiku na více místech (zažil jsem to už hodněkrát a nakonec to způsobí zhroucení projektu, který už nepůjde rozumně upravovat bez velkých chyb).

Navrhuju udělat jednu private metodu, která místo `back` bude vracet true a jinak false. A dvě public metody, které si po svém zareagují na to, že se něco změnilo:

```php
public static function prihlasovatkoZpracuj(...) {
  if (self::prihlasovatkoZpracujData(...)) {
    back();
  }
}

public static function prihlasovatkoZpracujJSON(...) {
  self::prihlasovatkoZpracujData(...);
}
```

:warning: je tu jedna změna v logice, která nevím jestli je schválně. V originále je `back`, které okamžitě způsobí redirect a **exit**, takže poslední logika se nespustí, pokud se něco zpracovalo
```php
        if ($parametry & self::PLUSMINUS_KAZDY) {
            self::plusminusZpracuj();
        }
```
ale v nové metodě se to **spustí vždy**. Je to OK?

2025-03-08 16:30 UTC, Sciator commented on ui/src/pages/program/components/vstupy/OdhlasitAktivituModal.tsx
> +              .then(async () => načtiRok(GAMECON_KONSTANTY.ROCNIK))
doděláno

2025-03-08 16:46 UTC, Sciator commented on model/Aktivita/Aktivita.php
> +    public static function prihlasovatkoZpracujJSON(?Uzivatel $u, ?Uzivatel $prihlasujici, $parametry = 0)
:)

2025-03-08 16:47 UTC, Sciator commented
@jaroslavtyc za mě ready až na lehce provizorní nápis loading ale to chce čas :)

2025-04-21 15:09 UTC, Sciator commented
nenašel jsem k tomuhle trello kartu tak jsem založil znovu i s novým PR 
https://trello.com/c/PRpsrQbC/1318-program-p%C5%99ihl%C3%A1%C5%A1en%C3%AD-na-aktivitu-bez-znovuna%C4%8Dten%C3%AD

2025-04-21 15:09 UTC, closed without merging